name: eeg_preprocessing
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy
    - pandas
    - scipy
    - matplotlib
    - seaborn
    - scikit-learn
    - "pomegranate<1.0.0"
    - pyedflib
    - lspopt
    - mne
    - h5py
    - six
    - ipykernel
    - ipython
    - ipympl
    - edfio
    - -e .