"""Dataset discovery, data-location resolution, and readers for pipeline artifacts."""

from .loading import (
    HYPNOGRAM_SUFFIX,
    PREDICTIONS_SUFFIX,
    SEGMENTS_SUFFIX,
    SIGNAL_TABLE_SUFFIXES,
    ScoredRef,
    align_vectors,
    find_scored,
    find_somnotate_predictions,
    get_csv_dir,
    get_predictions_dir,
    get_test_root,
    hypnogram_path,
    list_csv_files,
    load_aligned_vectors,
    load_manual_vectors_from_csvs,
    load_raw_signals_from_csv,
    load_recording_arrays,
    load_scored_recording,
    load_scores,
    load_segments,
    load_signal_table,
    load_somnotate_predictions,
    load_somnotate_vector,
    load_testing_csv,
    prediction_path,
    segments_path,
)
from .paths import (
    RecordingRef,
    find_recordings,
    get_derivatives_root,
    get_raw_root,
    normalize_subjid,
)
from .selectors import parse_date_range, parse_dates, parse_subjects
from .style import ensure_style

__all__ = [
    "HYPNOGRAM_SUFFIX",
    "PREDICTIONS_SUFFIX",
    "RecordingRef",
    "SEGMENTS_SUFFIX",
    "SIGNAL_TABLE_SUFFIXES",
    "ScoredRef",
    "align_vectors",
    "ensure_style",
    "find_recordings",
    "find_scored",
    "find_somnotate_predictions",
    "get_csv_dir",
    "get_derivatives_root",
    "get_predictions_dir",
    "get_raw_root",
    "get_test_root",
    "hypnogram_path",
    "list_csv_files",
    "load_aligned_vectors",
    "load_manual_vectors_from_csvs",
    "load_raw_signals_from_csv",
    "load_recording_arrays",
    "load_scored_recording",
    "load_scores",
    "load_segments",
    "load_signal_table",
    "load_somnotate_predictions",
    "load_somnotate_vector",
    "load_testing_csv",
    "normalize_subjid",
    "parse_date_range",
    "parse_dates",
    "parse_subjects",
    "prediction_path",
    "segments_path",
]
